/*

 BACKGROUND1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Xande\Desktop\GBTD\Sprites\Simple_Background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Background1Width 40
#define Background1Height 18
#define Background1Bank 0

extern unsigned char Background1[];

/* End of BACKGROUND1.H */
