/*

 MAZE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\xande\OneDrive\Desktop\GBTD\Tile Sets\wall_and_goal_collision_test.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MazeWidth 20
#define MazeHeight 18
#define MazeBank 0

extern unsigned char Maze[];

/* End of MAZE.H */
